import { NextRequest, NextResponse } from 'next/server'

const tables = ['portal_news', 'portal_deadlines', 'portal_formats', 'portal_leaders'] as const
const PASSWORD = '262310'
const headers = () => ({ apikey: process.env.SUPABASE_SERVICE_ROLE_KEY!, Authorization: `Bearer ${process.env.SUPABASE_SERVICE_ROLE_KEY!}`, 'Content-Type': 'application/json', Prefer: 'return=representation' })
async function db(path: string, options?: RequestInit) { return fetch(`${process.env.SUPABASE_URL}/rest/v1/${path}`, { ...options, headers: { ...headers(), ...(options?.headers || {}) }, cache: 'no-store' }) }
function validType(type: string): type is (typeof tables)[number] { return tables.includes(type as (typeof tables)[number]) }
export async function GET() { const rows = await Promise.all(tables.map(async (table) => { const response = await db(`${table}?select=*&order=created_at.desc`); return [table, response.ok ? await response.json() : []] as const })); return NextResponse.json(Object.fromEntries(rows)) }
export async function POST(request: NextRequest) { const body = await request.json(); if (body.password !== PASSWORD) return NextResponse.json({ error: 'No autorizado' }, { status: 401 }); const { password: _password, type, ...record } = body; if (!validType(type)) return NextResponse.json({ error: 'Tipo inválido' }, { status: 400 }); const response = await db(type, { method: 'POST', body: JSON.stringify(record) }); return NextResponse.json(await response.json(), { status: response.status }) }
export async function PATCH(request: NextRequest) { const body = await request.json(); if (body.password !== PASSWORD) return NextResponse.json({ error: 'No autorizado' }, { status: 401 }); const { password: _password, type, id, ...record } = body; if (!validType(type) || !id) return NextResponse.json({ error: 'Solicitud inválida' }, { status: 400 }); const response = await db(`${type}?id=eq.${encodeURIComponent(id)}`, { method: 'PATCH', body: JSON.stringify(record) }); return NextResponse.json(await response.json(), { status: response.status }) }
export async function DELETE(request: NextRequest) { const body = await request.json(); if (body.password !== PASSWORD || !validType(body.type) || !body.id) return NextResponse.json({ error: 'No autorizado' }, { status: 401 }); const response = await db(`${body.type}?id=eq.${encodeURIComponent(body.id)}`, { method: 'DELETE' }); return NextResponse.json({ ok: response.ok }, { status: response.ok ? 200 : response.status }) }
